version: "3.8"

services:
  tee:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
      - tee:/app/packages/client-twitter/src/tweetcache
      - tee:/app/db.sqlite
    env_file:
      - .env # Explicitly load environment variables from the .env file
    ports:
      - "3000:3000"
    restart: always
    environment:
      # Explicitly override sensitive keys if needed
      TWITTER_DRY_RUN=false

volumes:
  tee:
